-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1:3306
-- Время создания: Фев 25 2018 г., 09:08
-- Версия сервера: 5.5.53
-- Версия PHP: 7.0.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `finance`
--

-- --------------------------------------------------------

--
-- Структура таблицы `articles`
--

CREATE TABLE `articles` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `text` text NOT NULL,
  `date` datetime NOT NULL,
  `views` int(11) NOT NULL,
  `likes` int(11) NOT NULL,
  `category` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `articles`
--

INSERT INTO `articles` (`id`, `title`, `text`, `date`, `views`, `likes`, `category`) VALUES
(1, 'Lorem Ipsum1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ipsum ipsum, faucibus in erat non, elementum vulputate massa. Nulla massa ex, vehicula tempus mattis at, sollicitudin sit amet quam. Mauris blandit velit vel tempus finibus. Mauris vitae semper felis, ut euismod urna. Proin sodales elementum diam varius tristique. Sed non feugiat magna. Proin quis arcu id dui lobortis feugiat. Quisque lacinia, lectus sed mollis egestas, ligula risus lobortis magna, ut dignissim sapien sem quis leo. Nunc accumsan est et erat tempus feugiat. Nam condimentum egestas turpis faucibus pharetra. Praesent a imperdiet arcu, quis ultricies felis.\r\n\r\nDuis nec orci suscipit, suscipit nibh ut, ultricies dolor. Nullam lacus enim, efficitur sit amet nisl et, interdum ullamcorper nisi. Sed venenatis consequat sem, ut aliquam massa rutrum quis. Donec felis felis, commodo in quam at, aliquam auctor turpis. Duis faucibus suscipit tellus, a ultrices magna interdum vitae. Maecenas quis sollicitudin dui. Curabitur consectetur sapien tincidunt metus consectetur suscipit.\r\n\r\nNunc eget sem quis eros porttitor dictum quis at lorem. Proin gravida bibendum augue, lobortis venenatis orci semper nec. Donec convallis dui eu consequat varius. Maecenas id augue vulputate, sollicitudin nulla vitae, dapibus libero. Vivamus in sagittis erat. Sed feugiat tortor purus, dapibus cursus ipsum pellentesque non. Maecenas id sagittis purus. Suspendisse facilisis magna vitae aliquet laoreet. Cras elementum orci aliquam, gravida magna non, varius urna.\r\n\r\nPellentesque vehicula mi sed urna rhoncus dapibus quis ut erat. Duis molestie neque sed lectus congue, a dapibus eros pretium. Pellentesque eget dolor mi. Maecenas id dignissim orci. Phasellus fringilla pellentesque tincidunt. Curabitur dictum, erat ac maximus tincidunt, mi turpis volutpat est, a accumsan tellus massa vel purus. Pellentesque quis sem nulla. Mauris dignissim ante sed ornare semper. Nam arcu nunc, convallis eget scelerisque at, tristique in leo. Praesent hendrerit a nibh nec aliquam. Suspendisse porta libero at ex pharetra, sed suscipit magna consectetur.\r\n\r\nFusce at finibus dolor. Nullam euismod nibh vitae lorem efficitur sollicitudin. Sed vestibulum, tortor eget ultrices blandit, augue justo mattis magna, vel euismod enim enim sed elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin et tincidunt felis, et venenatis ipsum. Aliquam congue vitae enim at accumsan. Aliquam ut accumsan ligula, id placerat odio. Mauris a rutrum arcu. Mauris in nulla aliquam ante placerat blandit. Fusce lacinia sed neque quis rutrum. Morbi lobortis nulla non orci ultrices eleifend. Fusce lacinia eros quis nisl volutpat, sit amet pellentesque quam dictum.', '2018-02-06 07:21:00', 1, 1, 'stocks'),
(2, 'Lorem Ipsum2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ipsum ipsum, faucibus in erat non, elementum vulputate massa. Nulla massa ex, vehicula tempus mattis at, sollicitudin sit amet quam. Mauris blandit velit vel tempus finibus. Mauris vitae semper felis, ut euismod urna. Proin sodales elementum diam varius tristique. Sed non feugiat magna. Proin quis arcu id dui lobortis feugiat. Quisque lacinia, lectus sed mollis egestas, ligula risus lobortis magna, ut dignissim sapien sem quis leo. Nunc accumsan est et erat tempus feugiat. Nam condimentum egestas turpis faucibus pharetra. Praesent a imperdiet arcu, quis ultricies felis.\r\n\r\nDuis nec orci suscipit, suscipit nibh ut, ultricies dolor. Nullam lacus enim, efficitur sit amet nisl et, interdum ullamcorper nisi. Sed venenatis consequat sem, ut aliquam massa rutrum quis. Donec felis felis, commodo in quam at, aliquam auctor turpis. Duis faucibus suscipit tellus, a ultrices magna interdum vitae. Maecenas quis sollicitudin dui. Curabitur consectetur sapien tincidunt metus consectetur suscipit.\r\n\r\nNunc eget sem quis eros porttitor dictum quis at lorem. Proin gravida bibendum augue, lobortis venenatis orci semper nec. Donec convallis dui eu consequat varius. Maecenas id augue vulputate, sollicitudin nulla vitae, dapibus libero. Vivamus in sagittis erat. Sed feugiat tortor purus, dapibus cursus ipsum pellentesque non. Maecenas id sagittis purus. Suspendisse facilisis magna vitae aliquet laoreet. Cras elementum orci aliquam, gravida magna non, varius urna.\r\n\r\nPellentesque vehicula mi sed urna rhoncus dapibus quis ut erat. Duis molestie neque sed lectus congue, a dapibus eros pretium. Pellentesque eget dolor mi. Maecenas id dignissim orci. Phasellus fringilla pellentesque tincidunt. Curabitur dictum, erat ac maximus tincidunt, mi turpis volutpat est, a accumsan tellus massa vel purus. Pellentesque quis sem nulla. Mauris dignissim ante sed ornare semper. Nam arcu nunc, convallis eget scelerisque at, tristique in leo. Praesent hendrerit a nibh nec aliquam. Suspendisse porta libero at ex pharetra, sed suscipit magna consectetur.\r\n\r\nFusce at finibus dolor. Nullam euismod nibh vitae lorem efficitur sollicitudin. Sed vestibulum, tortor eget ultrices blandit, augue justo mattis magna, vel euismod enim enim sed elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin et tincidunt felis, et venenatis ipsum. Aliquam congue vitae enim at accumsan. Aliquam ut accumsan ligula, id placerat odio. Mauris a rutrum arcu. Mauris in nulla aliquam ante placerat blandit. Fusce lacinia sed neque quis rutrum. Morbi lobortis nulla non orci ultrices eleifend. Fusce lacinia eros quis nisl volutpat, sit amet pellentesque quam dictum.', '2018-02-06 07:22:00', 2, 2, 'stocks'),
(3, 'Lorem Ipsum3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ipsum ipsum, faucibus in erat non, elementum vulputate massa. Nulla massa ex, vehicula tempus mattis at, sollicitudin sit amet quam. Mauris blandit velit vel tempus finibus. Mauris vitae semper felis, ut euismod urna. Proin sodales elementum diam varius tristique. Sed non feugiat magna. Proin quis arcu id dui lobortis feugiat. Quisque lacinia, lectus sed mollis egestas, ligula risus lobortis magna, ut dignissim sapien sem quis leo. Nunc accumsan est et erat tempus feugiat. Nam condimentum egestas turpis faucibus pharetra. Praesent a imperdiet arcu, quis ultricies felis.\r\n\r\nDuis nec orci suscipit, suscipit nibh ut, ultricies dolor. Nullam lacus enim, efficitur sit amet nisl et, interdum ullamcorper nisi. Sed venenatis consequat sem, ut aliquam massa rutrum quis. Donec felis felis, commodo in quam at, aliquam auctor turpis. Duis faucibus suscipit tellus, a ultrices magna interdum vitae. Maecenas quis sollicitudin dui. Curabitur consectetur sapien tincidunt metus consectetur suscipit.\r\n\r\nNunc eget sem quis eros porttitor dictum quis at lorem. Proin gravida bibendum augue, lobortis venenatis orci semper nec. Donec convallis dui eu consequat varius. Maecenas id augue vulputate, sollicitudin nulla vitae, dapibus libero. Vivamus in sagittis erat. Sed feugiat tortor purus, dapibus cursus ipsum pellentesque non. Maecenas id sagittis purus. Suspendisse facilisis magna vitae aliquet laoreet. Cras elementum orci aliquam, gravida magna non, varius urna.\r\n\r\nPellentesque vehicula mi sed urna rhoncus dapibus quis ut erat. Duis molestie neque sed lectus congue, a dapibus eros pretium. Pellentesque eget dolor mi. Maecenas id dignissim orci. Phasellus fringilla pellentesque tincidunt. Curabitur dictum, erat ac maximus tincidunt, mi turpis volutpat est, a accumsan tellus massa vel purus. Pellentesque quis sem nulla. Mauris dignissim ante sed ornare semper. Nam arcu nunc, convallis eget scelerisque at, tristique in leo. Praesent hendrerit a nibh nec aliquam. Suspendisse porta libero at ex pharetra, sed suscipit magna consectetur.\r\n\r\nFusce at finibus dolor. Nullam euismod nibh vitae lorem efficitur sollicitudin. Sed vestibulum, tortor eget ultrices blandit, augue justo mattis magna, vel euismod enim enim sed elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin et tincidunt felis, et venenatis ipsum. Aliquam congue vitae enim at accumsan. Aliquam ut accumsan ligula, id placerat odio. Mauris a rutrum arcu. Mauris in nulla aliquam ante placerat blandit. Fusce lacinia sed neque quis rutrum. Morbi lobortis nulla non orci ultrices eleifend. Fusce lacinia eros quis nisl volutpat, sit amet pellentesque quam dictum.', '2018-02-06 07:23:00', 3, 3, 'etf'),
(4, 'Lorem Ipsum4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ipsum ipsum, faucibus in erat non, elementum vulputate massa. Nulla massa ex, vehicula tempus mattis at, sollicitudin sit amet quam. Mauris blandit velit vel tempus finibus. Mauris vitae semper felis, ut euismod urna. Proin sodales elementum diam varius tristique. Sed non feugiat magna. Proin quis arcu id dui lobortis feugiat. Quisque lacinia, lectus sed mollis egestas, ligula risus lobortis magna, ut dignissim sapien sem quis leo. Nunc accumsan est et erat tempus feugiat. Nam condimentum egestas turpis faucibus pharetra. Praesent a imperdiet arcu, quis ultricies felis.\r\n\r\nDuis nec orci suscipit, suscipit nibh ut, ultricies dolor. Nullam lacus enim, efficitur sit amet nisl et, interdum ullamcorper nisi. Sed venenatis consequat sem, ut aliquam massa rutrum quis. Donec felis felis, commodo in quam at, aliquam auctor turpis. Duis faucibus suscipit tellus, a ultrices magna interdum vitae. Maecenas quis sollicitudin dui. Curabitur consectetur sapien tincidunt metus consectetur suscipit.\r\n\r\nNunc eget sem quis eros porttitor dictum quis at lorem. Proin gravida bibendum augue, lobortis venenatis orci semper nec. Donec convallis dui eu consequat varius. Maecenas id augue vulputate, sollicitudin nulla vitae, dapibus libero. Vivamus in sagittis erat. Sed feugiat tortor purus, dapibus cursus ipsum pellentesque non. Maecenas id sagittis purus. Suspendisse facilisis magna vitae aliquet laoreet. Cras elementum orci aliquam, gravida magna non, varius urna.\r\n\r\nPellentesque vehicula mi sed urna rhoncus dapibus quis ut erat. Duis molestie neque sed lectus congue, a dapibus eros pretium. Pellentesque eget dolor mi. Maecenas id dignissim orci. Phasellus fringilla pellentesque tincidunt. Curabitur dictum, erat ac maximus tincidunt, mi turpis volutpat est, a accumsan tellus massa vel purus. Pellentesque quis sem nulla. Mauris dignissim ante sed ornare semper. Nam arcu nunc, convallis eget scelerisque at, tristique in leo. Praesent hendrerit a nibh nec aliquam. Suspendisse porta libero at ex pharetra, sed suscipit magna consectetur.\r\n\r\nFusce at finibus dolor. Nullam euismod nibh vitae lorem efficitur sollicitudin. Sed vestibulum, tortor eget ultrices blandit, augue justo mattis magna, vel euismod enim enim sed elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin et tincidunt felis, et venenatis ipsum. Aliquam congue vitae enim at accumsan. Aliquam ut accumsan ligula, id placerat odio. Mauris a rutrum arcu. Mauris in nulla aliquam ante placerat blandit. Fusce lacinia sed neque quis rutrum. Morbi lobortis nulla non orci ultrices eleifend. Fusce lacinia eros quis nisl volutpat, sit amet pellentesque quam dictum.', '2018-02-06 07:23:00', 1, 1, 'etf'),
(5, 'Lorem Ipsum5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ipsum ipsum, faucibus in erat non, elementum vulputate massa. Nulla massa ex, vehicula tempus mattis at, sollicitudin sit amet quam. Mauris blandit velit vel tempus finibus. Mauris vitae semper felis, ut euismod urna. Proin sodales elementum diam varius tristique. Sed non feugiat magna. Proin quis arcu id dui lobortis feugiat. Quisque lacinia, lectus sed mollis egestas, ligula risus lobortis magna, ut dignissim sapien sem quis leo. Nunc accumsan est et erat tempus feugiat. Nam condimentum egestas turpis faucibus pharetra. Praesent a imperdiet arcu, quis ultricies felis.\r\n\r\nDuis nec orci suscipit, suscipit nibh ut, ultricies dolor. Nullam lacus enim, efficitur sit amet nisl et, interdum ullamcorper nisi. Sed venenatis consequat sem, ut aliquam massa rutrum quis. Donec felis felis, commodo in quam at, aliquam auctor turpis. Duis faucibus suscipit tellus, a ultrices magna interdum vitae. Maecenas quis sollicitudin dui. Curabitur consectetur sapien tincidunt metus consectetur suscipit.\r\n\r\nNunc eget sem quis eros porttitor dictum quis at lorem. Proin gravida bibendum augue, lobortis venenatis orci semper nec. Donec convallis dui eu consequat varius. Maecenas id augue vulputate, sollicitudin nulla vitae, dapibus libero. Vivamus in sagittis erat. Sed feugiat tortor purus, dapibus cursus ipsum pellentesque non. Maecenas id sagittis purus. Suspendisse facilisis magna vitae aliquet laoreet. Cras elementum orci aliquam, gravida magna non, varius urna.\r\n\r\nPellentesque vehicula mi sed urna rhoncus dapibus quis ut erat. Duis molestie neque sed lectus congue, a dapibus eros pretium. Pellentesque eget dolor mi. Maecenas id dignissim orci. Phasellus fringilla pellentesque tincidunt. Curabitur dictum, erat ac maximus tincidunt, mi turpis volutpat est, a accumsan tellus massa vel purus. Pellentesque quis sem nulla. Mauris dignissim ante sed ornare semper. Nam arcu nunc, convallis eget scelerisque at, tristique in leo. Praesent hendrerit a nibh nec aliquam. Suspendisse porta libero at ex pharetra, sed suscipit magna consectetur.\r\n\r\nFusce at finibus dolor. Nullam euismod nibh vitae lorem efficitur sollicitudin. Sed vestibulum, tortor eget ultrices blandit, augue justo mattis magna, vel euismod enim enim sed elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin et tincidunt felis, et venenatis ipsum. Aliquam congue vitae enim at accumsan. Aliquam ut accumsan ligula, id placerat odio. Mauris a rutrum arcu. Mauris in nulla aliquam ante placerat blandit. Fusce lacinia sed neque quis rutrum. Morbi lobortis nulla non orci ultrices eleifend. Fusce lacinia eros quis nisl volutpat, sit amet pellentesque quam dictum.', '2018-02-06 07:24:00', 5, 4, 'other'),
(6, 'Lorem Ipsum6', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ipsum ipsum, faucibus in erat non, elementum vulputate massa. Nulla massa ex, vehicula tempus mattis at, sollicitudin sit amet quam. Mauris blandit velit vel tempus finibus. Mauris vitae semper felis, ut euismod urna. Proin sodales elementum diam varius tristique. Sed non feugiat magna. Proin quis arcu id dui lobortis feugiat. Quisque lacinia, lectus sed mollis egestas, ligula risus lobortis magna, ut dignissim sapien sem quis leo. Nunc accumsan est et erat tempus feugiat. Nam condimentum egestas turpis faucibus pharetra. Praesent a imperdiet arcu, quis ultricies felis.\r\n\r\nDuis nec orci suscipit, suscipit nibh ut, ultricies dolor. Nullam lacus enim, efficitur sit amet nisl et, interdum ullamcorper nisi. Sed venenatis consequat sem, ut aliquam massa rutrum quis. Donec felis felis, commodo in quam at, aliquam auctor turpis. Duis faucibus suscipit tellus, a ultrices magna interdum vitae. Maecenas quis sollicitudin dui. Curabitur consectetur sapien tincidunt metus consectetur suscipit.\r\n\r\nNunc eget sem quis eros porttitor dictum quis at lorem. Proin gravida bibendum augue, lobortis venenatis orci semper nec. Donec convallis dui eu consequat varius. Maecenas id augue vulputate, sollicitudin nulla vitae, dapibus libero. Vivamus in sagittis erat. Sed feugiat tortor purus, dapibus cursus ipsum pellentesque non. Maecenas id sagittis purus. Suspendisse facilisis magna vitae aliquet laoreet. Cras elementum orci aliquam, gravida magna non, varius urna.\r\n\r\nPellentesque vehicula mi sed urna rhoncus dapibus quis ut erat. Duis molestie neque sed lectus congue, a dapibus eros pretium. Pellentesque eget dolor mi. Maecenas id dignissim orci. Phasellus fringilla pellentesque tincidunt. Curabitur dictum, erat ac maximus tincidunt, mi turpis volutpat est, a accumsan tellus massa vel purus. Pellentesque quis sem nulla. Mauris dignissim ante sed ornare semper. Nam arcu nunc, convallis eget scelerisque at, tristique in leo. Praesent hendrerit a nibh nec aliquam. Suspendisse porta libero at ex pharetra, sed suscipit magna consectetur.\r\n\r\nFusce at finibus dolor. Nullam euismod nibh vitae lorem efficitur sollicitudin. Sed vestibulum, tortor eget ultrices blandit, augue justo mattis magna, vel euismod enim enim sed elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin et tincidunt felis, et venenatis ipsum. Aliquam congue vitae enim at accumsan. Aliquam ut accumsan ligula, id placerat odio. Mauris a rutrum arcu. Mauris in nulla aliquam ante placerat blandit. Fusce lacinia sed neque quis rutrum. Morbi lobortis nulla non orci ultrices eleifend. Fusce lacinia eros quis nisl volutpat, sit amet pellentesque quam dictum.', '2018-02-06 07:25:00', 0, 0, 'other'),
(7, 'Lorem Ipsum7', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ipsum ipsum, faucibus in erat non, elementum vulputate massa. Nulla massa ex, vehicula tempus mattis at, sollicitudin sit amet quam. Mauris blandit velit vel tempus finibus. Mauris vitae semper felis, ut euismod urna. Proin sodales elementum diam varius tristique. Sed non feugiat magna. Proin quis arcu id dui lobortis feugiat. Quisque lacinia, lectus sed mollis egestas, ligula risus lobortis magna, ut dignissim sapien sem quis leo. Nunc accumsan est et erat tempus feugiat. Nam condimentum egestas turpis faucibus pharetra. Praesent a imperdiet arcu, quis ultricies felis.\r\n\r\nDuis nec orci suscipit, suscipit nibh ut, ultricies dolor. Nullam lacus enim, efficitur sit amet nisl et, interdum ullamcorper nisi. Sed venenatis consequat sem, ut aliquam massa rutrum quis. Donec felis felis, commodo in quam at, aliquam auctor turpis. Duis faucibus suscipit tellus, a ultrices magna interdum vitae. Maecenas quis sollicitudin dui. Curabitur consectetur sapien tincidunt metus consectetur suscipit.\r\n\r\nNunc eget sem quis eros porttitor dictum quis at lorem. Proin gravida bibendum augue, lobortis venenatis orci semper nec. Donec convallis dui eu consequat varius. Maecenas id augue vulputate, sollicitudin nulla vitae, dapibus libero. Vivamus in sagittis erat. Sed feugiat tortor purus, dapibus cursus ipsum pellentesque non. Maecenas id sagittis purus. Suspendisse facilisis magna vitae aliquet laoreet. Cras elementum orci aliquam, gravida magna non, varius urna.\r\n\r\nPellentesque vehicula mi sed urna rhoncus dapibus quis ut erat. Duis molestie neque sed lectus congue, a dapibus eros pretium. Pellentesque eget dolor mi. Maecenas id dignissim orci. Phasellus fringilla pellentesque tincidunt. Curabitur dictum, erat ac maximus tincidunt, mi turpis volutpat est, a accumsan tellus massa vel purus. Pellentesque quis sem nulla. Mauris dignissim ante sed ornare semper. Nam arcu nunc, convallis eget scelerisque at, tristique in leo. Praesent hendrerit a nibh nec aliquam. Suspendisse porta libero at ex pharetra, sed suscipit magna consectetur.\r\n\r\nFusce at finibus dolor. Nullam euismod nibh vitae lorem efficitur sollicitudin. Sed vestibulum, tortor eget ultrices blandit, augue justo mattis magna, vel euismod enim enim sed elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin et tincidunt felis, et venenatis ipsum. Aliquam congue vitae enim at accumsan. Aliquam ut accumsan ligula, id placerat odio. Mauris a rutrum arcu. Mauris in nulla aliquam ante placerat blandit. Fusce lacinia sed neque quis rutrum. Morbi lobortis nulla non orci ultrices eleifend. Fusce lacinia eros quis nisl volutpat, sit amet pellentesque quam dictum.', '2018-02-06 07:25:00', 0, 0, 'other'),
(8, 'Lorem Ipsum8', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ipsum ipsum, faucibus in erat non, elementum vulputate massa. Nulla massa ex, vehicula tempus mattis at, sollicitudin sit amet quam. Mauris blandit velit vel tempus finibus. Mauris vitae semper felis, ut euismod urna. Proin sodales elementum diam varius tristique. Sed non feugiat magna. Proin quis arcu id dui lobortis feugiat. Quisque lacinia, lectus sed mollis egestas, ligula risus lobortis magna, ut dignissim sapien sem quis leo. Nunc accumsan est et erat tempus feugiat. Nam condimentum egestas turpis faucibus pharetra. Praesent a imperdiet arcu, quis ultricies felis.\r\n\r\nDuis nec orci suscipit, suscipit nibh ut, ultricies dolor. Nullam lacus enim, efficitur sit amet nisl et, interdum ullamcorper nisi. Sed venenatis consequat sem, ut aliquam massa rutrum quis. Donec felis felis, commodo in quam at, aliquam auctor turpis. Duis faucibus suscipit tellus, a ultrices magna interdum vitae. Maecenas quis sollicitudin dui. Curabitur consectetur sapien tincidunt metus consectetur suscipit.\r\n\r\nNunc eget sem quis eros porttitor dictum quis at lorem. Proin gravida bibendum augue, lobortis venenatis orci semper nec. Donec convallis dui eu consequat varius. Maecenas id augue vulputate, sollicitudin nulla vitae, dapibus libero. Vivamus in sagittis erat. Sed feugiat tortor purus, dapibus cursus ipsum pellentesque non. Maecenas id sagittis purus. Suspendisse facilisis magna vitae aliquet laoreet. Cras elementum orci aliquam, gravida magna non, varius urna.\r\n\r\nPellentesque vehicula mi sed urna rhoncus dapibus quis ut erat. Duis molestie neque sed lectus congue, a dapibus eros pretium. Pellentesque eget dolor mi. Maecenas id dignissim orci. Phasellus fringilla pellentesque tincidunt. Curabitur dictum, erat ac maximus tincidunt, mi turpis volutpat est, a accumsan tellus massa vel purus. Pellentesque quis sem nulla. Mauris dignissim ante sed ornare semper. Nam arcu nunc, convallis eget scelerisque at, tristique in leo. Praesent hendrerit a nibh nec aliquam. Suspendisse porta libero at ex pharetra, sed suscipit magna consectetur.\r\n\r\nFusce at finibus dolor. Nullam euismod nibh vitae lorem efficitur sollicitudin. Sed vestibulum, tortor eget ultrices blandit, augue justo mattis magna, vel euismod enim enim sed elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin et tincidunt felis, et venenatis ipsum. Aliquam congue vitae enim at accumsan. Aliquam ut accumsan ligula, id placerat odio. Mauris a rutrum arcu. Mauris in nulla aliquam ante placerat blandit. Fusce lacinia sed neque quis rutrum. Morbi lobortis nulla non orci ultrices eleifend. Fusce lacinia eros quis nisl volutpat, sit amet pellentesque quam dictum.', '2018-02-06 07:22:00', 0, 0, 'stocks'),
(9, 'Lorem Ipsum9', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ipsum ipsum, faucibus in erat non, elementum vulputate massa. Nulla massa ex, vehicula tempus mattis at, sollicitudin sit amet quam. Mauris blandit velit vel tempus finibus. Mauris vitae semper felis, ut euismod urna. Proin sodales elementum diam varius tristique. Sed non feugiat magna. Proin quis arcu id dui lobortis feugiat. Quisque lacinia, lectus sed mollis egestas, ligula risus lobortis magna, ut dignissim sapien sem quis leo. Nunc accumsan est et erat tempus feugiat. Nam condimentum egestas turpis faucibus pharetra. Praesent a imperdiet arcu, quis ultricies felis.\r\n\r\nDuis nec orci suscipit, suscipit nibh ut, ultricies dolor. Nullam lacus enim, efficitur sit amet nisl et, interdum ullamcorper nisi. Sed venenatis consequat sem, ut aliquam massa rutrum quis. Donec felis felis, commodo in quam at, aliquam auctor turpis. Duis faucibus suscipit tellus, a ultrices magna interdum vitae. Maecenas quis sollicitudin dui. Curabitur consectetur sapien tincidunt metus consectetur suscipit.\r\n\r\nNunc eget sem quis eros porttitor dictum quis at lorem. Proin gravida bibendum augue, lobortis venenatis orci semper nec. Donec convallis dui eu consequat varius. Maecenas id augue vulputate, sollicitudin nulla vitae, dapibus libero. Vivamus in sagittis erat. Sed feugiat tortor purus, dapibus cursus ipsum pellentesque non. Maecenas id sagittis purus. Suspendisse facilisis magna vitae aliquet laoreet. Cras elementum orci aliquam, gravida magna non, varius urna.\r\n\r\nPellentesque vehicula mi sed urna rhoncus dapibus quis ut erat. Duis molestie neque sed lectus congue, a dapibus eros pretium. Pellentesque eget dolor mi. Maecenas id dignissim orci. Phasellus fringilla pellentesque tincidunt. Curabitur dictum, erat ac maximus tincidunt, mi turpis volutpat est, a accumsan tellus massa vel purus. Pellentesque quis sem nulla. Mauris dignissim ante sed ornare semper. Nam arcu nunc, convallis eget scelerisque at, tristique in leo. Praesent hendrerit a nibh nec aliquam. Suspendisse porta libero at ex pharetra, sed suscipit magna consectetur.\r\n\r\nFusce at finibus dolor. Nullam euismod nibh vitae lorem efficitur sollicitudin. Sed vestibulum, tortor eget ultrices blandit, augue justo mattis magna, vel euismod enim enim sed elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin et tincidunt felis, et venenatis ipsum. Aliquam congue vitae enim at accumsan. Aliquam ut accumsan ligula, id placerat odio. Mauris a rutrum arcu. Mauris in nulla aliquam ante placerat blandit. Fusce lacinia sed neque quis rutrum. Morbi lobortis nulla non orci ultrices eleifend. Fusce lacinia eros quis nisl volutpat, sit amet pellentesque quam dictum.', '2018-02-06 07:23:00', 1, 1, 'etf'),
(10, 'Lorem Ipsum10', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ipsum ipsum, faucibus in erat non, elementum vulputate massa. Nulla massa ex, vehicula tempus mattis at, sollicitudin sit amet quam. Mauris blandit velit vel tempus finibus. Mauris vitae semper felis, ut euismod urna. Proin sodales elementum diam varius tristique. Sed non feugiat magna. Proin quis arcu id dui lobortis feugiat. Quisque lacinia, lectus sed mollis egestas, ligula risus lobortis magna, ut dignissim sapien sem quis leo. Nunc accumsan est et erat tempus feugiat. Nam condimentum egestas turpis faucibus pharetra. Praesent a imperdiet arcu, quis ultricies felis.\r\n\r\nDuis nec orci suscipit, suscipit nibh ut, ultricies dolor. Nullam lacus enim, efficitur sit amet nisl et, interdum ullamcorper nisi. Sed venenatis consequat sem, ut aliquam massa rutrum quis. Donec felis felis, commodo in quam at, aliquam auctor turpis. Duis faucibus suscipit tellus, a ultrices magna interdum vitae. Maecenas quis sollicitudin dui. Curabitur consectetur sapien tincidunt metus consectetur suscipit.\r\n\r\nNunc eget sem quis eros porttitor dictum quis at lorem. Proin gravida bibendum augue, lobortis venenatis orci semper nec. Donec convallis dui eu consequat varius. Maecenas id augue vulputate, sollicitudin nulla vitae, dapibus libero. Vivamus in sagittis erat. Sed feugiat tortor purus, dapibus cursus ipsum pellentesque non. Maecenas id sagittis purus. Suspendisse facilisis magna vitae aliquet laoreet. Cras elementum orci aliquam, gravida magna non, varius urna.\r\n\r\nPellentesque vehicula mi sed urna rhoncus dapibus quis ut erat. Duis molestie neque sed lectus congue, a dapibus eros pretium. Pellentesque eget dolor mi. Maecenas id dignissim orci. Phasellus fringilla pellentesque tincidunt. Curabitur dictum, erat ac maximus tincidunt, mi turpis volutpat est, a accumsan tellus massa vel purus. Pellentesque quis sem nulla. Mauris dignissim ante sed ornare semper. Nam arcu nunc, convallis eget scelerisque at, tristique in leo. Praesent hendrerit a nibh nec aliquam. Suspendisse porta libero at ex pharetra, sed suscipit magna consectetur.\r\n\r\nFusce at finibus dolor. Nullam euismod nibh vitae lorem efficitur sollicitudin. Sed vestibulum, tortor eget ultrices blandit, augue justo mattis magna, vel euismod enim enim sed elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin et tincidunt felis, et venenatis ipsum. Aliquam congue vitae enim at accumsan. Aliquam ut accumsan ligula, id placerat odio. Mauris a rutrum arcu. Mauris in nulla aliquam ante placerat blandit. Fusce lacinia sed neque quis rutrum. Morbi lobortis nulla non orci ultrices eleifend. Fusce lacinia eros quis nisl volutpat, sit amet pellentesque quam dictum.', '2018-02-06 07:23:00', 1, 1, 'etf'),
(11, 'Lorem Ipsum11', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ipsum ipsum, faucibus in erat non, elementum vulputate massa. Nulla massa ex, vehicula tempus mattis at, sollicitudin sit amet quam. Mauris blandit velit vel tempus finibus. Mauris vitae semper felis, ut euismod urna. Proin sodales elementum diam varius tristique. Sed non feugiat magna. Proin quis arcu id dui lobortis feugiat. Quisque lacinia, lectus sed mollis egestas, ligula risus lobortis magna, ut dignissim sapien sem quis leo. Nunc accumsan est et erat tempus feugiat. Nam condimentum egestas turpis faucibus pharetra. Praesent a imperdiet arcu, quis ultricies felis.\r\n\r\nDuis nec orci suscipit, suscipit nibh ut, ultricies dolor. Nullam lacus enim, efficitur sit amet nisl et, interdum ullamcorper nisi. Sed venenatis consequat sem, ut aliquam massa rutrum quis. Donec felis felis, commodo in quam at, aliquam auctor turpis. Duis faucibus suscipit tellus, a ultrices magna interdum vitae. Maecenas quis sollicitudin dui. Curabitur consectetur sapien tincidunt metus consectetur suscipit.\r\n\r\nNunc eget sem quis eros porttitor dictum quis at lorem. Proin gravida bibendum augue, lobortis venenatis orci semper nec. Donec convallis dui eu consequat varius. Maecenas id augue vulputate, sollicitudin nulla vitae, dapibus libero. Vivamus in sagittis erat. Sed feugiat tortor purus, dapibus cursus ipsum pellentesque non. Maecenas id sagittis purus. Suspendisse facilisis magna vitae aliquet laoreet. Cras elementum orci aliquam, gravida magna non, varius urna.\r\n\r\nPellentesque vehicula mi sed urna rhoncus dapibus quis ut erat. Duis molestie neque sed lectus congue, a dapibus eros pretium. Pellentesque eget dolor mi. Maecenas id dignissim orci. Phasellus fringilla pellentesque tincidunt. Curabitur dictum, erat ac maximus tincidunt, mi turpis volutpat est, a accumsan tellus massa vel purus. Pellentesque quis sem nulla. Mauris dignissim ante sed ornare semper. Nam arcu nunc, convallis eget scelerisque at, tristique in leo. Praesent hendrerit a nibh nec aliquam. Suspendisse porta libero at ex pharetra, sed suscipit magna consectetur.\r\n\r\nFusce at finibus dolor. Nullam euismod nibh vitae lorem efficitur sollicitudin. Sed vestibulum, tortor eget ultrices blandit, augue justo mattis magna, vel euismod enim enim sed elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin et tincidunt felis, et venenatis ipsum. Aliquam congue vitae enim at accumsan. Aliquam ut accumsan ligula, id placerat odio. Mauris a rutrum arcu. Mauris in nulla aliquam ante placerat blandit. Fusce lacinia sed neque quis rutrum. Morbi lobortis nulla non orci ultrices eleifend. Fusce lacinia eros quis nisl volutpat, sit amet pellentesque quam dictum.', '2018-02-06 07:22:00', 2, 2, 'stocks');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `articles`
--
ALTER TABLE `articles`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
